user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/xml;
  client_max_body_size 20m;
  include /etc/nginx/conf.d/*.conf;
}
